/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./components/AppAlert.vue')['default']
    AppTable: typeof import('./components/AppTable.vue')['default']
    NotificationBell: typeof import('./components/NotificationBell.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetOrdersRevenue: typeof import('./components/widgets/orders/WidgetOrdersRevenue.vue')['default']
    WidgetOrdersSummary: typeof import('./components/widgets/orders/WidgetOrdersSummary.vue')['default']
    WidgetSettingsButton: typeof import('./components/widgets/WidgetSettingsButton.vue')['default']
    WidgetStat: typeof import('./components/widgets/WidgetStat.vue')['default']
    WidgetTopCategories: typeof import('./components/widgets/WidgetTopCategories.vue')['default']
    WidgetTopProducts: typeof import('./components/widgets/WidgetTopProducts.vue')['default']
  }
}
