<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);MSG0005</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.ListStartupServices" Version="1.1.4"/>
    <PackageReference Include="Ardalis.Result" Version="10.1.0"/>
    <PackageReference Include="Ardalis.SharedKernel" Version="5.0.0"/>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0"/>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.11" />
    <PackageReference Include="Scriban" Version="7.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0"/>
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Api.Core\\Api.Core.csproj"/>
    <ProjectReference Include="..\\Api.UseCases\\Api.UseCases.csproj"/>
    <ProjectReference Include="..\\Api.Infrastructure\\Api.Infrastructure.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.Development.json" />
  </ItemGroup>

</Project>
